// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/actor/application.proto

package actor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加的请求
type ApplicationAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain   string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`      // 域的uuid
	Name     string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`         // 应用名
	Version  string `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`   // 应用版本
	Program  string `protobuf:"bytes,12,opt,name=program,proto3" json:"program,omitempty"`   // 可执行文件
	Location string `protobuf:"bytes,13,opt,name=location,proto3" json:"location,omitempty"` // 安装路径
	Url      string `protobuf:"bytes,21,opt,name=url,proto3" json:"url,omitempty"`           // 下载地址
}

func (x *ApplicationAddRequest) Reset() {
	*x = ApplicationAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actor_application_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationAddRequest) ProtoMessage() {}

func (x *ApplicationAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actor_application_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationAddRequest.ProtoReflect.Descriptor instead.
func (*ApplicationAddRequest) Descriptor() ([]byte, []int) {
	return file_proto_actor_application_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationAddRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ApplicationAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationAddRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApplicationAddRequest) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *ApplicationAddRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ApplicationAddRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 移除的请求
type ApplicationRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 应用的uuid
}

func (x *ApplicationRemoveRequest) Reset() {
	*x = ApplicationRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actor_application_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationRemoveRequest) ProtoMessage() {}

func (x *ApplicationRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actor_application_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationRemoveRequest.ProtoReflect.Descriptor instead.
func (*ApplicationRemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_actor_application_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationRemoveRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 列举的请求
type ApplicationListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移值
	Count  int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`   // 数量
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`  // 域的uuid
}

func (x *ApplicationListRequest) Reset() {
	*x = ApplicationListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actor_application_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationListRequest) ProtoMessage() {}

func (x *ApplicationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actor_application_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationListRequest.ProtoReflect.Descriptor instead.
func (*ApplicationListRequest) Descriptor() ([]byte, []int) {
	return file_proto_actor_application_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ApplicationListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ApplicationListRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// 列举的回复
type ApplicationListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      *Status              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`           // 状态
	Total       int64                `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`            // 总数
	Application []*ApplicationEntity `protobuf:"bytes,3,rep,name=application,proto3" json:"application,omitempty"` // 应用实体列表
}

func (x *ApplicationListResponse) Reset() {
	*x = ApplicationListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actor_application_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationListResponse) ProtoMessage() {}

func (x *ApplicationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actor_application_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationListResponse.ProtoReflect.Descriptor instead.
func (*ApplicationListResponse) Descriptor() ([]byte, []int) {
	return file_proto_actor_application_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationListResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ApplicationListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ApplicationListResponse) GetApplication() []*ApplicationEntity {
	if x != nil {
		return x.Application
	}
	return nil
}

var File_proto_actor_application_proto protoreflect.FileDescriptor

var file_proto_actor_application_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xa5, 0x01, 0x0a, 0x15, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x15, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2e, 0x0a, 0x18, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x16, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x92, 0x01, 0x0a, 0x17, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x3a, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xd6, 0x01,
	0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a,
	0x03, 0x41, 0x64, 0x64, 0x12, 0x1c, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x06, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x42, 0x6c,
	0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x3b, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_actor_application_proto_rawDescOnce sync.Once
	file_proto_actor_application_proto_rawDescData = file_proto_actor_application_proto_rawDesc
)

func file_proto_actor_application_proto_rawDescGZIP() []byte {
	file_proto_actor_application_proto_rawDescOnce.Do(func() {
		file_proto_actor_application_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_actor_application_proto_rawDescData)
	})
	return file_proto_actor_application_proto_rawDescData
}

var file_proto_actor_application_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_actor_application_proto_goTypes = []interface{}{
	(*ApplicationAddRequest)(nil),    // 0: actor.ApplicationAddRequest
	(*ApplicationRemoveRequest)(nil), // 1: actor.ApplicationRemoveRequest
	(*ApplicationListRequest)(nil),   // 2: actor.ApplicationListRequest
	(*ApplicationListResponse)(nil),  // 3: actor.ApplicationListResponse
	(*Status)(nil),                   // 4: actor.Status
	(*ApplicationEntity)(nil),        // 5: actor.ApplicationEntity
	(*BlankResponse)(nil),            // 6: actor.BlankResponse
}
var file_proto_actor_application_proto_depIdxs = []int32{
	4, // 0: actor.ApplicationListResponse.status:type_name -> actor.Status
	5, // 1: actor.ApplicationListResponse.application:type_name -> actor.ApplicationEntity
	0, // 2: actor.Application.Add:input_type -> actor.ApplicationAddRequest
	1, // 3: actor.Application.Remove:input_type -> actor.ApplicationRemoveRequest
	2, // 4: actor.Application.List:input_type -> actor.ApplicationListRequest
	6, // 5: actor.Application.Add:output_type -> actor.BlankResponse
	6, // 6: actor.Application.Remove:output_type -> actor.BlankResponse
	3, // 7: actor.Application.List:output_type -> actor.ApplicationListResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_actor_application_proto_init() }
func file_proto_actor_application_proto_init() {
	if File_proto_actor_application_proto != nil {
		return
	}
	file_proto_actor_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_actor_application_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actor_application_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actor_application_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actor_application_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_actor_application_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_actor_application_proto_goTypes,
		DependencyIndexes: file_proto_actor_application_proto_depIdxs,
		MessageInfos:      file_proto_actor_application_proto_msgTypes,
	}.Build()
	File_proto_actor_application_proto = out.File
	file_proto_actor_application_proto_rawDesc = nil
	file_proto_actor_application_proto_goTypes = nil
	file_proto_actor_application_proto_depIdxs = nil
}
